import type { IMentor } from '@/types/mentors.type'

export const mentorsMock: IMentor[] = [
  {
    id: 1,
    name: 'Jessica Jane',
    role: 'Web Developer',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    tasks: 40,
    rating: 4.7,
    reviews: 150,
    followed: false,
    bio: 'Hi, I’m Jessica Jane. I am a frontend developer at Hamari University majoring in Web.',
  },
  {
    id: 2,
    name: 'Abraham Lincoln',
    role: '3D Designer',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    tasks: 32,
    rating: 4.9,
    reviews: 120,
    followed: true,
    bio: '3D designer with strong experience in modeling and animation.',
  },
  {
    id: 3,
    name: 'Curious George',
    role: 'UI/UX Designer',
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    tasks: 40,
    rating: 4.7,
    reviews: 90,
    followed: false,
    bio: 'Passionate about user-centered design and clean interfaces.',
  },
  {
    id: 4,
    name: 'Alex Stanton',
    role: 'UI/UX Designer',
    avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
    tasks: 60,
    rating: 4.9,
    reviews: 180,
    followed: true,
    bio: 'Oxford University alumnus, UI/UX designer with product mindset.',
  },
  {
    id: 5,
    name: 'Antoine Griezmann',
    role: 'Android Developer',
    avatar: 'https://randomuser.me/api/portraits/men/77.jpg',
    tasks: 50,
    rating: 4.8,
    reviews: 130,
    followed: false,
    bio: 'Android engineer at Google, Kotlin & Jetpack Compose.',
  },
  {
    id: 6,
    name: 'Anna White',
    role: '3D Designer',
    avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
    tasks: 60,
    rating: 4.8,
    reviews: 87,
    followed: true,
    bio: 'Professional 3D designer working with international brands.',
  },
  {
    id: 7,
    name: 'Richard Kyle',
    role: '2D Designer',
    avatar: 'https://randomuser.me/api/portraits/men/54.jpg',
    tasks: 60,
    rating: 4.7,
    reviews: 70,
    followed: false,
    bio: '2D designer focusing on illustrations and branding.',
  },
  {
    id: 8,
    name: 'Julia Philips',
    role: 'iOS Developer',
    avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
    tasks: 60,
    rating: 4.9,
    reviews: 99,
    followed: true,
    bio: 'Senior iOS engineer, Swift & SwiftUI expert.',
  },
  {
    id: 9,
    name: 'Daniel Craig',
    role: 'Backend Developer',
    avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    tasks: 75,
    rating: 4.6,
    reviews: 110,
    followed: false,
    bio: 'Backend developer specializing in Node.js and PostgreSQL.',
  },
  {
    id: 10,
    name: 'Sophia Turner',
    role: 'Product Designer',
    avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
    tasks: 55,
    rating: 4.8,
    reviews: 140,
    followed: true,
    bio: 'Product designer creating delightful user experiences.',
  },
  {
    id: 11,
    name: 'Michael Brown',
    role: 'Data Analyst',
    avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
    tasks: 48,
    rating: 4.5,
    reviews: 60,
    followed: false,
    bio: 'Data analyst with strong Python and SQL background.',
  },
  {
    id: 12,
    name: 'Emily Clark',
    role: 'QA Engineer',
    avatar: 'https://randomuser.me/api/portraits/women/30.jpg',
    tasks: 42,
    rating: 4.7,
    reviews: 75,
    followed: false,
    bio: 'QA engineer focused on automation and test reliability.',
  },
]
